# 一些常量

# K线相关列名
CANDLE_DATETIME_COLUMN = 'candle_begin_time'
CANDLE_OPEN_COLUMN = 'open'
CANDLE_HIGH_COLUMN = 'high'
CANDLE_LOW_COLUMN = 'low'
CANDLE_CLOSE_COLUMN = 'close'
CANDLE_VOLUME_COLUMN = 'volume'
CANDLE_COLUMNS = [CANDLE_DATETIME_COLUMN, CANDLE_OPEN_COLUMN, CANDLE_HIGH_COLUMN, CANDLE_LOW_COLUMN,
                  CANDLE_CLOSE_COLUMN, CANDLE_VOLUME_COLUMN]

# 买卖信号列名
SIGNAL_COLUMN = 'signal'
# 持仓列名
POSITION_COLUMN = 'position'
